### ISSUE TITLE
Kernel Panic on removing ipfw_mod module on Linux ubuntu 3.13.0-93-generic and Linux ubuntu 4.4.0-31-generic

### ISSUE THREAD

**Issue by abhishekismdhn** [luigirizzo/dummynet#17]
6816 Aug 27 14:26:59 ubuntu kernel: [57910.400145] ipfw_module_init loaded
6817 Aug 27 14:27:09 ubuntu kernel: [57920.872769] BUG: unable to handle kernel NULL pointer dereference at           (null)
6818 Aug 27 14:27:09 ubuntu kernel: [57920.872775] IP: [<          (null)>](null)
6819 Aug 27 14:27:09 ubuntu kernel: [57920.872777] PGD 0
6820 Aug 27 14:27:09 ubuntu kernel: [57920.872778] Oops: 0010 [#1] SMP
6821 Aug 27 14:27:09 ubuntu kernel: [57920.872782] Modules linked in: ipfw_mod(OX-) iptable_mangle ip_tables x_tables sch_netem cls_u32 sch_htb v     mw_vsock_vmci_transport vsock pci_stub vboxpci(OX) vboxnetadp(OX) vboxnetflt(OX) vboxdrv(OX) hid_generic snd_ens1371 usbhid snd_ac97_codec a     c97_bus hid gameport snd_pcm coretemp crct10dif_pclmul crc32_pclmul vmw_balloon snd_page_alloc snd_seq_midi aesni_intel snd_seq_midi_event a     es_x86_64 lrw gf128mul glue_helper snd_rawmidi ablk_helper cryptd serio_raw snd_seq snd_seq_device snd_timer snd soundcore bnep rfcomm vmwgf     x bluetooth ttm drm parport_pc binfmt_misc i2c_piix4 vmw_vmci ppdev shpchp mac_hid lp parport psmouse ahci libahci vmw_pvscsi pata_acpi mpts     pi mptscsih e1000 mptbase vmxnet3 floppy
6822 Aug 27 14:27:09 ubuntu kernel: [57920.872808] CPU: 1 PID: 9856 Comm: rmmod Tainted: G           OX 3.13.0-93-generic #140-Ubuntu
6823 Aug 27 14:27:09 ubuntu kernel: [57920.872810] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.0     0 07/02/2015
6824 Aug 27 14:27:09 ubuntu kernel: [57920.872811] task: ffff8800b6f76000 ti: ffff8801e831e000 task.ti: ffff8801e831e000
6825 Aug 27 14:27:09 ubuntu kernel: [57920.872812] RIP: 0010:[<0000000000000000>]  [<          (null)>](null)
6826 Aug 27 14:27:09 ubuntu kernel: [57920.872813] RSP: 0018:ffff8801e831fe88  EFLAGS: 00010283
6827 Aug 27 14:27:09 ubuntu kernel: [57920.872814] RAX: ffffffff81cdad90 RBX: ffffffff81cdad80 RCX: 00000000c0000100
6828 Aug 27 14:27:09 ubuntu kernel: [57920.872815] RDX: ffff8801e831fe70 RSI: ffffffffa04205f8 RDI: ffffffff81cdad80
6829 Aug 27 14:27:09 ubuntu kernel: [57920.872815] RBP: ffff8801e831fea8 R08: ffff8801e831e000 R09: 0000000000000000
6830 Aug 27 14:27:09 ubuntu kernel: [57920.872816] R10: 0000000000000000 R11: 0000000000000000 R12: ffffffffa0420520
6831 Aug 27 14:27:09 ubuntu kernel: [57920.872817] R13: ffffffffa04205f8 R14: 0000000000000000 R15: 00007fefcb9b4250
6832 Aug 27 14:27:09 ubuntu kernel: [57920.872818] FS:  00007fefca86f740(0000) GS:ffff8801f0020000(0000) knlGS:0000000000000000
6833 Aug 27 14:27:09 ubuntu kernel: [57920.872818] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
6834 Aug 27 14:27:09 ubuntu kernel: [57920.872819] CR2: 0000000000000000 CR3: 00000001e9cb3000 CR4: 00000000001407e0
6835 Aug 27 14:27:09 ubuntu kernel: [57920.872849] Stack:
6836 Aug 27 14:27:09 ubuntu kernel: [57920.872850]  ffffffff8165d773 ffffffffa04205f8 ffffffffa04205c0 0000000000000800
6837 Aug 27 14:27:09 ubuntu kernel: [57920.872851]  ffff8801e831fec0 ffffffff8165c72e 0000000000000001 ffff8801e831fee0
6838 Aug 27 14:27:09 ubuntu kernel: [57920.872853]  ffffffff8165c77c 0000000000000000 ffffffffa0420640 ffff8801e831fef0
6839 Aug 27 14:27:09 ubuntu kernel: [57920.872854] Call Trace:
6840 Aug 27 14:27:09 ubuntu kernel: [57920.872868]  [<ffffffff8165d773>] ? nf_queue_nf_hook_drop+0x43/0x60
6841 Aug 27 14:27:09 ubuntu kernel: [57920.872870]  [<ffffffff8165c72e>] nf_unregister_hook+0x6e/0x80
6842 Aug 27 14:27:09 ubuntu kernel: [57920.872871]  [<ffffffff8165c77c>] nf_unregister_hooks+0x3c/0x50
6843 Aug 27 14:27:09 ubuntu kernel: [57920.872877]  [<ffffffffa041b5f7>] cleanup_module+0x15/0xa1e [ipfw_mod]
6844 Aug 27 14:27:09 ubuntu kernel: [57920.872884]  [<ffffffff810e3542>] SyS_delete_module+0x162/0x200
6845 Aug 27 14:27:09 ubuntu kernel: [57920.872891]  [<ffffffff8173aa1d>] system_call_fastpath+0x1a/0x1f
6846 Aug 27 14:27:09 ubuntu kernel: [57920.872892] Code:  Bad RIP value.
6847 Aug 27 14:27:09 ubuntu kernel: [57920.872895] RIP  [<          (null)>](null)
6848 Aug 27 14:27:09 ubuntu kernel: [57920.872896]  RSP <ffff8801e831fe88>
6849 Aug 27 14:27:09 ubuntu kernel: [57920.872896] CR2: 0000000000000000
6850 Aug 27 14:27:09 ubuntu kernel: [57920.872899] ---[ end trace 7721148db371bd6b ]---

**Comment by shamidrasool** [comment]
Mine doesn't even build on Linux ubuntu 4.4.0-31-generic.

or ‘ipfw_ops[0]’) [-Werror]
/tmp/dummynet-master/kipfw-mod/ipfw2_mod.c:834:17: error: initialization from incompatible pointer type [-Werror]
                 .hook           = call_ipfw,
                 ^
/tmp/dummynet-master/kipfw-mod/ipfw2_mod.c:834:17: error: (near initialization for ‘ipfw_ops[1].hook’) [-Werror]
/tmp/dummynet-master/kipfw-mod/ipfw2_mod.c:838:3: error: unknown field ‘owner’ specified in initializer
   SET_MOD_OWNER
   ^
/tmp/dummynet-master/kipfw-mod/ipfw2_mod.c:838:3: error: excess elements in struct initializer [-Werror]
/tmp/dummynet-master/kipfw-mod/ipfw2_mod.c:838:3: error: (near initialization for ‘ipfw_ops[1]’) [-Werror]
cc1: all warnings being treated as errors
make[3]: *** [/tmp/dummynet-master/kipfw-mod/ipfw2_mod.o] Error 1
make[2]: *** [_module_/tmp/dummynet-master/kipfw-mod] Error 2
make[2]: Leaving directory `/usr/src/linux-headers-4.4.0-31-generic'
make[1]: *** [kipfw] Error 2
make[1]: Leaving directory `/tmp/dummynet-master/kipfw-mod'
make: *** [kipfw] Error 2
